### ISSUE TITLE
Update packer key mappings

### ISSUE THREAD

**Issue by rsharifnasab** [1995parham/elievim#17]
After switching to lazy.nvim, it might be a good idea to update key mappings to trigger lazy-related functions instead of packer functions. ([this file](https://github.com/1995parham/elievim/blob/1f8539b3c9d96eb04b332acbd442b02b3b353d96/lua/keymap/init.lua#L16))

**Comment by 1995parham** [comment]
Thanks, @rsharifnasab jan, I will fix it ASAP.
